---
title: "Abstract"
author: "IW"
date: "April, 2019"
output: html_document
---
##First thoughts

The study of death coverage is a problematic topic in countries without an integrated system of register data, when some cross-cheks can be done. At national level exists indirect methods (DDM), coming from the formal demography, that they depends of string assumptions that can be hold in small areas. At a province level there was some experiences in Argentina, applying surveys in important cities, and only focused in child mortality. 

The society always tried to leave a sign/message about death events, specially the closest social network (relatives, friends). One of this was the obituary, a message in the public media about the death event and a social ritual around this (burial, crematorium, etc.), that in the SXXI sounds a bit old-fashioned, but is very influenced by the age of the relatives and with the culture and the segmentation urban/rural.

Access to this data is more easy since this paw prints are posted in internet. Typically this messages have information about the death date, the age at death, and the complete name (and with this a big certainty about the sex). This information can be matched with the death register in some small area, so this combination would do a unique case to be compared. It can be included in the recent research about using internet and social media content to study demographic behaviors.

The steps for this research will (could) be:

1) Because no omission rate will be possible to estimate (there is a clear bias of closest social network to publish an obituary in the online newspaper). The main result will be the % of obituaries (unique death persons) that aren't included in the register, or are included but with erroneous information. This results would be interpreted in terms of 'fuzzy' probabilities. 
2) Select a newspaper web page with important coverage, and that its location would be in the center of the department (smaller are in the official register). Also the information needs to be structured in a handle way.
3) Do the web scraping and text mining to extract the useful information and unique deaths.
5) compare death distribution by age and sex, and watch representativeness.
6) Define a 'fuzzy' scale to belonging. For example, a decreasing fuzzy belonging would be:  
        a) same month of death, sex, age  
        b) month+-1 of death, same sex and age  
        c) same month of death, sex, age+-5  
        d) month+-1 of death, same sex and age+-5  
        e) else  
  Study fuzzy properties and possible applications  
7) results and conclusions